
name: 'Dependabot Group Merge Approve Action'
description: 'Automatically group dependabot pull requests into a single one and merge it'
author: 'kuvaus'
branding:
  color: "green"
  icon: "git-pull-request"

inputs:
  botname:
    description: 'Name of the bot. E.g. dependabot or renovate'
    required: false
  require_green:
    description: 'Require the pull requests to be green'
    required: false    
  combined_pr_name:
    description: 'Branch name for the combined pull request'
    required: false    
  ignore:
    description: 'Ignore pull requests with this name'
    required: false
  close_merged:
    description: 'Close merged pull requests automatically'
    required: false
  auto_merge_combined:
    description: 'Automatically merge the combined pull request'
    required: false
  day:
    description: 'Run on a specific day'
    required: false
  hour:
    description: 'Run after a specific hour'
    required: false
  wait:
    description: 'Wait N seconds before starting'
    required: false
  merge_individually:
    description: 'Merge pull requests individually instead of combining'
    required: false

# runs:
   using: node20
   main: dist/index.js
