
name: 'Dependabot Group Merge Approve Action'
description: 'Automatically group dependabot pull requests into a single one and merge it'
author: 'kuvaus'
branding:
  color: "green"
  icon: "git-pull-request"

inputs:
  botname:
    description: 'Name of the bot. E.g. dependabot or renovate'
    required: false
  require_green:
    description: 'Require the pull requests to be green'
    required: false    
  combined_pr_name:
    description: 'Branch name for the combined pull request'
    required: false    
  ignore:
    description: 'Ignore pull requests with this name'
    required: false
  close_merged:
    description: 'Close merged pull requests automatically'
    required: false
  auto_merge_combined:
    description: 'Automatically merge the combined pull request'
    required: false
  day:
    description: 'Run on a specific day'
    required: false
  hour:
    description: 'Run after a specific hour'
    required: false
  wait:
    description: 'Wait N seconds before starting'
    required: false
  merge_individually:
    description: 'Merge pull requests individually instead of combining'
    required: false

# runs:
#   using: node16
#   main: dist/index.js


# This part is temporary to enable Node 20 support

runs:
  using: composite
  steps:

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version || '20' }}

    - name: Action
      run: |
        node ${{ github.action_path }}/dist/index.js
        echo "::set-output name=releasenotes::value1"
      shell: ${{ (runner.os == 'Windows' && 'pwsh') || 'bash' }}
      env:
        INPUT_BOTNAME:                       ${{ inputs.botname }}
        INPUT_REQUIRE_GREEN:                 ${{ inputs.require_green }}
        INPUT_COMBINED_PR_NAME:              ${{ inputs.combined_pr_name }}
        INPUT_IGNORE:                        ${{ inputs.ignore }}
        INPUT_CLOSE_MERGED:                  ${{ inputs.close_merged }}
        INPUT_AUTO_MERGE_COMBINED:           ${{ inputs.auto_merge_combined }}
        INPUT_DAY:                           ${{ inputs.day }}
        INPUT_HOUR:                          ${{ inputs.hour }}
        INPUT_WAIT:                          ${{ inputs.wait }}
        INPUT_MERGE_INDIVIDUALLY:            ${{ inputs.merge_individually }}


