name: Merge dependabot pull requests automatically

on:
  pull_request_target:
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    name: Merge dependabot pull requests automatically
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Merge dependabot pull requests automatically
        uses: kuvaus/dependabot-group-merge-approve-action@v2
        with:
          merge_individually: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
